spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  config:
    import: "optional:configserver:${APP_CONFIG_SERVER_URI:http://localhost:8888}"
  cloud:
    config:
      enabled: ${APP_CONFIG_ENABLED:true}
      fail-fast: ${APP_CONFIG_FAIL_FAST:false}
      label: ${APP_CONFIG_LABEL:main}
      discovery:
        enabled: ${APP_CONFIG_DISCOVERY_ENABLED:false}
        service-id: ${APP_CONFIG_DISCOVERY_SERVICE_ID:config-server}
    gateway:
      discovery:
        locator:
          enabled: false
  main:
    web-application-type: reactive

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,prometheus}
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      validate-group-membership: false
      group:
        liveness:
          include: livenessState,ping
        readiness:
          include: readinessState,discoveryComposite
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      system: ${MANAGEMENT_METRICS_TAG_SYSTEM:arkab2b}
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.arka.platform.apigateway: ${LOG_LEVEL_APP:INFO}
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] [%X{traceId:-}/%X{correlationId:-}] %logger{36} - %msg%n}

app:
  observability:
    trace-id-header: ${APP_OBSERVABILITY_TRACE_ID_HEADER:X-Trace-Id}
    correlation-id-header: ${APP_OBSERVABILITY_CORRELATION_ID_HEADER:X-Correlation-Id}
  security:
    jwt:
      issuer: ${APP_SECURITY_JWT_ISSUER:identity-access-service}
      allowed-audiences: ${APP_SECURITY_JWT_ALLOWED_AUDIENCES:arka-b2b}
      clock-skew-seconds: ${APP_SECURITY_JWT_CLOCK_SKEW_SECONDS:60}
      jwks-uri: ${APP_SECURITY_JWT_JWKS_URI:http://localhost:8081/.well-known/jwks.json}
