spring:
  r2dbc:
    url: ${APP_PROD_R2DBC_URL}
    username: ${APP_PROD_R2DBC_USERNAME}
    password: ${APP_PROD_R2DBC_PASSWORD}
  data:
    redis:
      host: ${APP_PROD_REDIS_HOST}
      port: ${APP_PROD_REDIS_PORT:6379}
      password: ${APP_PROD_REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: ${APP_PROD_KAFKA_BOOTSTRAP_SERVERS}

app:
  database:
    schema:
      initialize-on-startup: ${APP_DATABASE_SCHEMA_INITIALIZE_ON_STARTUP:false}
